version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./htdocs:/var/www/html
      - ./php-custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./.wp-cli:/var/wp-cli/
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      APACHE_RUN_USER: wordpress
      APACHE_RUN_GROUP: wordpress
      WP_CLI_CACHE_PATH: /var/wp-cli/cache
      WP_CLI_PACKAGES_PATH: /var/wp-cli/packages

